### ISSUE TITLE
UI form : input bottom line

### ISSUE THREAD

**Issue by Jeremy38100** [Jeremy38100/Todo_IHM#4]
![capture d ecran 2017-12-09 a 14 18 18](https://user-images.githubusercontent.com/10939826/33795980-f695dfb4-dceb-11e7-965f-465a326e70ad.png)

As you can see on this picture : on some input, the bottom line is display twice.
Maybe it's a bug from materialize-css
@MugnierJu @medrag

**Comment by medrag** [comment]
it's not a bug the item Modal and the List Modal are not coded with css materialize yet, we still working on it
